# Generated by Django 5.0.3 on 2024-05-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=1000)),
                ('no_people', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('day_of_week', models.CharField(max_length=100)),
            ],
        ),
    ]
